language: python
sudo: false

matrix:
    include:
        - python: 3.6
          env: TOXENV=py3

install:
  - travis_retry pip install tox

script:
  - travis_retry tox -v

cache:
  directories:
    - $HOME/.cache/pip
